FROM node:alpine
USER node


RUN mkdir -p /home/node/app 
WORKDIR /home/node/app

COPY --chown=node:node package.json .

RUN npm install --legacy-peer-deps

COPY --chown=node:node . . 

RUN npm install @angular/cli@11.2.0

# CMD ["npm","run","start"]

CMD node_modules/.bin/ng serve --host 0.0.0.0 --disable-host-check